-- AlterTable
ALTER TABLE "User" ADD COLUMN "weight" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN "height" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN "age"    INTEGER;
ALTER TABLE "User" ADD COLUMN "gender" TEXT;
